name: Makefile CI

on:
  push:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: newman install
        if: contains(github.event_name, 'push')
        run: sudo npm install -g newman

      - name: Setup
        if: contains(github.event_name, 'push')
        run: curl https://api.getpostman.com/collections/@POSTMAN_COLLECTION_ID?apikey=$POSTMAN_API_KEY &amp;amp;gt; api.json
        env:
          POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
          POSTMAN_COLLECTION_ID: ${{ secrets.POSTMAN_COLLECTION_ID }}

      - name: Unit Tests
        if: contains(github.event_name, 'push')
        run: newman run ./docs/postman/api.json

      - name: Cleanup
        if: always()
        run: rm -f ./docs/postman/api.json
